In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression

In [2]:
dataset = pd.read_csv('titanic.csv')
dataset

Passengerid   Age      Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
0               1  22.0    7.2500    0      1     0       0       0       0   
1               2  38.0   71.2833    1      1     0       0       0       0   
2               3  26.0    7.9250    1      0     0       0       0       0   
3               4  35.0   53.1000    1      1     0       0       0       0   
4               5  35.0    8.0500    0      0     0       0       0       0   
...           ...   ...       ...  ...    ...   ...     ...     ...     ...   
1304         1305  28.0    8.0500    0      0     0       0       0       0   
1305         1306  39.0  108.9000    1      0     0       0       0       0   
1306         1307  38.5    7.2500    0      0     0       0       0       0   
1307         1308  28.0    8.0500    0      0     0       0       0       0   
1308         1309  28.0   22.3583    0      1     0       0       0       0   

      zero.4  ...  zero.12  zero.13  zero.14  Pclass  zero.15  zero.16  \
0          0  ...        0        0        0       3        0        0   
1          0  ...        0        0        0       1        0        0   
2          0  ...        0        0        0       3        0        0   
3          0  ...        0        0        0       1        0        0   
4          0  ...        0        0        0       3        0        0   
...      ...  ...      ...      ...      ...     ...      ...      ...   
1304       0  ...        0        0        0       3        0        0   
1305       0  ...        0        0        0       1        0        0   
1306       0  ...        0        0        0       3        0        0   
1307       0  ...        0        0        0       3        0        0   
1308       0  ...        0        0        0       3        0        0   

      Embarked  zero.17  zero.18  2urvived  
0          2.0        0        0         0  
1          0.0        0        0         1  
2          2.0        0        0         1  
3          2.0        0        0         1  
4          2.0        0        0         0  
...        ...      ...      ...       ...  
1304       2.0        0        0         0  
1305       0.0        0        0         0  
1306       2.0        0        0         0  
1307       2.0        0        0         0  
1308       0.0        0        0         0  

[1309 rows x 28 columns]

In [4]:
dataset.describe()

Passengerid          Age         Fare          Sex        sibsp  \
count  1309.000000  1309.000000  1309.000000  1309.000000  1309.000000   
mean    655.000000    29.503186    33.281086     0.355997     0.498854   
std     378.020061    12.905241    51.741500     0.478997     1.041658   
min       1.000000     0.170000     0.000000     0.000000     0.000000   
25%     328.000000    22.000000     7.895800     0.000000     0.000000   
50%     655.000000    28.000000    14.454200     0.000000     0.000000   
75%     982.000000    35.000000    31.275000     1.000000     1.000000   
max    1309.000000    80.000000   512.329200     1.000000     8.000000   

         zero  zero.1  zero.2  zero.3  zero.4  ...  zero.12  zero.13  zero.14  \
count  1309.0  1309.0  1309.0  1309.0  1309.0  ...   1309.0   1309.0   1309.0   
mean      0.0     0.0     0.0     0.0     0.0  ...      0.0      0.0      0.0   
std       0.0     0.0     0.0     0.0     0.0  ...      0.0      0.0      0.0   
min       0.0     0.0     0.0     0.0     0.0  ...      0.0      0.0      0.0   
25%       0.0     0.0     0.0     0.0     0.0  ...      0.0      0.0      0.0   
50%       0.0     0.0     0.0     0.0     0.0  ...      0.0      0.0      0.0   
75%       0.0     0.0     0.0     0.0     0.0  ...      0.0      0.0      0.0   
max       0.0     0.0     0.0     0.0     0.0  ...      0.0      0.0      0.0   

            Pclass  zero.15  zero.16     Embarked  zero.17  zero.18  \
count  1309.000000   1309.0   1309.0  1307.000000   1309.0   1309.0   
mean      2.294882      0.0      0.0     1.492731      0.0      0.0   
std       0.837836      0.0      0.0     0.814626      0.0      0.0   
min       1.000000      0.0      0.0     0.000000      0.0      0.0   
25%       2.000000      0.0      0.0     1.000000      0.0      0.0   
50%       3.000000      0.0      0.0     2.000000      0.0      0.0   
75%       3.000000      0.0      0.0     2.000000      0.0      0.0   
max       3.000000      0.0      0.0     2.000000      0.0      0.0   

          2urvived  
count  1309.000000  
mean      0.261268  
std       0.439494  
min       0.000000  
25%       0.000000  
50%       0.000000  
75%       1.000000  
max       1.000000  

[8 rows x 28 columns]

In [6]:
dataset.dropna(inplace=True)
dataset.Embarked.unique()

array([2., 0., 1.])

In [7]:
from sklearn.model_selection import train_test_split

In [30]:
X_test = dataset[["Age", "Fare", "Sex", "Pclass"]].values
Y_test = dataset["2urvived"].values

In [31]:
X_test

array([[22.    ,  7.25  ,  0.    ,  3.    ],
       [38.    , 71.2833,  1.    ,  1.    ],
       [26.    ,  7.925 ,  1.    ,  3.    ],
       ...,
       [38.5   ,  7.25  ,  0.    ,  3.    ],
       [28.    ,  8.05  ,  0.    ,  3.    ],
       [28.    , 22.3583,  0.    ,  3.    ]])

In [32]:
Y_test

array([0, 1, 1, ..., 0, 0, 0])

In [33]:
model = LogisticRegression()
model.fit(X_test, Y_test)

LogisticRegression()

In [34]:
prediction = model.predict(X_test)
model.score(X_test, Y_test)

0.7834736036725325

In [38]:
new_data = [[10, 125, 1, 1]]
new_data = model.predict(new_data)
if new_data[0]:
    print("Survives!")
else:
    print("RIP")


Survives!
